export enum PedidoStatus {
  REGISTERED = 'REGISTERED',
  IN_PROCESS = 'IN_PROCESS',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

